cmd : >
  echo "Recherche de build";
  if [ -d build ];
    then echo "Suppression de build";
    rm build -r;
  fi;
  echo "Construction de build";
  mkdir build; cd build;
  conan install ..;
  echo "CMAKE PART";
  cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Release ..;
  cmake --build . --config "Release";
