# stages:
#   - build-and-test
#
# before_script:
#     - echo '#######################-BEGIN-##############################'
#     - echo 'Processing update and installs...'
#     - conan profile new default --detect
#     - conan profile update settings.compiler.libcxx=libstdc++11 default
#     - sudo apt update && sudo apt install -y libgtk2.0-dev libgl1-mesa-dev
#
# after_script:
#     - echo '########################-END-#############################'
#
# build-and-test-stage:
#     stage: build-and-test
#     script:
#         - echo "Building files..."
#         - rm -rf buildGCC
#         - mkdir buildGCC
#         - cd buildGCC
#         - conan install ..
#         - cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake ..
#         - cmake --build . --config "Release"
#         - echo "Running tests..."
#         - ctest

job:gcc:
  image: conanio/gcc9
  stage: gcc
  script:
    - echo "Hello gcc"

job:gcc:
  image: conanio/clang10
  stage: clang
  script:
    - echo "Hello clang"
