stages:
  - build
  - test

job:gcc:build:
  image: arthurviens/hpcai-2021:lob-conan-gcc9

  stage: build
  script:
    - echo 'Building ...'
    - if [ -d build ]; then rm build -r; fi
    - mkdir build
    - cd build
    - conan install ..
    - cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config "Release"
  artifacts:
      paths:
          - build/

job:gcc:test:
  image: arthurviens/hpcai-2021:lob-conan-gcc9
  stage: test
  script:
    - echo "Running tests..."
    - cd build
    - ctest
  dependencies:
    - job:gcc:build


job:clang:build:
  image: arthurviens/hpcai-2021:lob-conan-clang10

  stage: build
  script:
    - echo 'Building ...'
    - if [ -d build ]; then rm build -r; fi
    - mkdir build
    - cd build
    - conan install ..
    - cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config "Release"
  artifacts:
      paths:
          - build/

job:clang:test:
  image: arthurviens/hpcai-2021:lob-conan-clang10

  stage: test
  script:
    - echo "Running tests..."
    - cd build
    - ctest
  dependencies:
    - job:clang:build
