image: conanio/gcc9

stages:
  - build
  - test

build-stage:
    stage: build
    script:
        - echo "Updating apt ..."
        - sudo apt update && sudo apt upgrade
        - echo "Downloading libgtk2.0-dev libgl1-mesa-dev"
        - Y | sudo DEBIAN_FRONTEND=noninteractive apt install -y libgtk2.0-dev
        - Y | sudo DEBIAN_FRONTEND=noninteractive apt install -y libgl1-mesa-dev
        - echo "Building..."
        - if [ -d "build" ]; then rm -r "build"; fi
        - mkdir build
        - cd build
        - conan profile new default --detect
        - conan profile update settings.compiler.libcxx=libstdc++11 default
        - conan install ..
        - cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Debug ..
        - cmake --build .
    artifacts:
        paths:
            - build/


test-stage:
    stage: test
    script:
        - cd build
        - ctest
