before_script:
    - sudo apt-get update && sudo apt install -y libgtk2.0-dev libgl1-mesa-dev

stages:
  - build
  - test

build-stage:
    stage: build
    script:
        - echo "Building..."
        - cd /data
        - mkdir -p build && cd build
        - conan install ..
        - conan profile update settings.compiler.libcxx=libstdc++11 default
        - cmake -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake _DCMAKE_BUILD_TYPE=Debug ..
        - cmake --build .
    artifacts:
        paths:
            - build/

test-stage:
    stage: test
    script:
        - echo "Testing..."
        - test -f build/proof.txt